<img src="../images/icon/Technical-Stuff.png" alt="Technical-Stuff" style="width: 100px;float:left; margin-right:15px"/>
<br />

## What is a function?
***

Formally, a function is a useful device that groups together a set of statements so they can be run more than once. We can also specify parameters that can serve as inputs to the functions.


## Function Definition
***
In the syntax below:
- **def** is the keyword used to define functions
- arg1...argn, \*args and \*\*kwargs are function parameters (and are optional)
- The expression after the `return` keyword is the value returned to the caller (optional)

Now lets look at how we can create a function in python

# Python program to print Highest Common Factor (HCF) of two numbers:

In [1]:
def computeHCF(a, b):
    """
    Computing HCF of two numbers
    """
    smaller = b if a > b else a  #consice way of writing if else statement
    
    hcf = 1
    for i in range(1, smaller+1):
        if (a % i == 0) and (b % i == 0):
            hcf = i
    return hcf

num1 = 6
num2 = 36

print("H.C.F of {0} and {1} is: {2}".format(num1, num2, computeHCF(num1, num2)))

H.C.F of 6 and 36 is: 6


## Function Arguments
***
- Parameters may or may not have default values (in the example below, 'argn' has default value 3)
- A function parameter can be passed either by position or by key/name
- A function can accept a variable number of positional arguments (\*args)
- A function can accept a variable number of keyword arguments (\*\*kwargs)
- Function parameters are passed by object reference


### Default Arguments / Keyword Arguments
***
- Default arguments are those arguments which can be changed but their value remains the same if not given. An example of the same is given below.  


In [1]:
def double_the_number(num=5):
    return num * 2

print(double_the_number())

10


## Positional Arguments
***
- Positional arguments are those which are not followed by an equal sign (=) and default value. In this we need to provide an argument while calling the function, else we get an error. Here is an example below

In [2]:
def double_the_number(num):
    return num*2

print(double_the_number(5))

10


<img src="../images/icon/Technical-Stuff.png" alt="Technical-Stuff" style="width: 100px;float:left; margin-right:15px"/>
<br />

## Important Tip
***
- **Positional arguments** will always **precede** **Keyword arguments** while specifying both of them together in the same function. Below is an example of this

In [6]:
def function_name(arg1, arg2, *args, argn=3, **kwargs):
    print(arg1)
    print(arg2)
    print(args)
    print(argn)
    print(kwargs)
print(function_name('harshit',10,1,2,3,a=11,b=12))

harshit
10
(1, 2, 3)
3
{'a': 11, 'b': 12}
None


In [28]:
def multiplynums(*args):
    multiply=1
    for i in args:
        multiply *=i
    return multiply
nums=[3,4,5]
print(multiplynums(*nums))

60


In [31]:
def func(**kwargs):
    for k,v in kwargs.items():
        print(f"{k}:{v}")
d={'name':'harshit','age':24}
func(**d)
func(FirstName='SAJIB',LastName='HALDER')

name:harshit
age:24
FirstName:SAJIB
LastName:HALDER


<img src="../images/icon/Concept-Alert.png" alt="Technical-Stuff" style="width: 100px;float:left; margin-right:15px"/>
<br />

## Lambda
***
One of Pythons most useful (and for beginners, confusing) tools is the lambda expression. Lambda expressions allow us to create "anonymous" functions. This basically means we can quickly make ad-hoc functions without needing to properly define a function using def.

Function objects returned by running lambda expressions work exactly the same as those created and assigned by defs. There is key difference that makes lambda useful in specialized roles:

**Lambda's body is a single expression, not a block of statements.**
* Python supports the creation of anonymous functions at runtime, using a construct called **`lambda`**
* This approach is most commonly used when passing a simple function as an argument to another function.
* Lambdas are generally used in conjunction with typical functional concepts like `filter()`, `map()` and `reduce()`.

Now Lets slowly break down a lambda expression by deconstructing a function:

In [32]:
def square(num):
    result = num**2
    return result
square(3)

9

We can actually write this in one line (although it would be bad style to do so)

In [34]:
def square(num): return num**2
square(3)

9

This is the form of a function that a lambda expression intends to replicate. A lambda expression can then be written as:

In [35]:
square_lambda = lambda num: num**2

square_lambda(3)

9

In [37]:
add_lambda = lambda a,b: a+b

add_lambda(5,2)

7

# enumerate():

In [3]:
numbers = [10, 20, 30]

for index, num in enumerate(numbers,101):     # The enumerate() method adds counter to an iterable and returns it 
    print("index {0} has value {1}".format(index, num))   

index 101 has value 10
index 102 has value 20
index 103 has value 30


# filter():

In [5]:
def find_positive_number(num):
    """
    This function returns the positive number if num is positive
    """
    if num > 0:
        return num
    
number_list = range(-5, 5) #create a list with numbers from -5 to 5
print(list(number_list))

positive_num_lst = list(filter(find_positive_number, number_list))

print(positive_num_lst)


[-5, -4, -3, -2, -1, 0, 1, 2, 3, 4]
[1, 2, 3, 4]


# <img src="../images/icon/Technical-Stuff.png" alt="Technical-Stuff" style="width: 100px;float:left; margin-right:15px"/>
<br />

### `map`
***

map() is a function that takes in two arguments: a function and a sequence iterable. In the form: map(function, sequence) **`map(function, sequence)`**

The first argument is the name of a function and the second a sequence (e.g. a list). map() applies the function to all the elements of the sequence. It returns a new list with the elements changed by function.

When we went over list comprehension we created a small expression to convert Fahrenheit to Celsius. Let's do the same here but use map.

We'll start with two functions..

In [6]:
def fahrenheit(T):
    return ((float(9)/5)*T + 32)
def celsius(T):
    return (float(5)/9)*(T-32)
    
temp = [0, 22.5, 40,100]

Now lets see map() in action:

In [9]:
F_temps = list(map(fahrenheit, temp))

#Show
F_temps

[32.0, 72.5, 104.0, 212.0]

In [10]:
# Convert back
list(map(celsius, F_temps))

[0.0, 22.5, 40.0, 100.0]

In the example above we haven't used a lambda expression. By using lambda, we wouldn't have had to define and name the functions fahrenheit() and celsius().

<img src="../images/icon/Technical-Stuff.png" alt="Technical-Stuff" style="width: 100px;float:left; margin-right:15px"/>
<br />

## Important Tip
***
**`map`** is much more commonly used with lambda expressions since the entire purpose of map() is to save effort on having to create manual **`for `** loops.

map() can be applied to more than one iterable. The iterables have to have the same length.

For example lets map a lambda expression:


In [11]:
a = [1,2,3,4]
b = [5,6,7,8]
c = [9,10,11,12]

In [12]:
result=map(lambda x: (5.0/9)*(x - 32),a)
print(list(result))

[-17.22222222222222, -16.666666666666668, -16.11111111111111, -15.555555555555557]


In [13]:
numbers = [1, 2, 3, 4]

def powerOfTwo(num):
    return num ** 2

#using map() function
squared = list(map(powerOfTwo, numbers))
print(squared)


[1, 4, 9, 16]


# reduce():

In [14]:
lst = [1, 2, 3, 4]
#with reduce()
from functools import reduce # in Python 3.

def multiply(x,y):
    return x*y;

product = reduce(multiply, lst)
print(product)


24


<img src="../images/icon/Concept-Alert.png" alt="Concept-Alert" style="width: 100px;float:left; margin-right:15px"/>
<br />

# Object Oriented Programming
***

Object Oriented Programming (OOP) tends to be one of the major obstacles for beginners when they are first starting to learn Python.

There are many,many tutorials and lessons covering OOP so feel free to Google search other lessons too. 

For this lesson we will construct our knowledge of OOP in Python by building on the following topics:

* Objects
* Using the *class* keyword
* Creating class attributes
* Creating methods in a class
* Learning about Special Methods for classes

What we will basically be doing is exploring how we could create an Object type like a list. We've already learned about how to create functions. So lets explore Objects in general:


## Objects
***

In Python, everything is an object. Remember from previous lectures we can use type() to check the type of object something is:

In [2]:
print (type(1))
print (type([]))
print (type(()))
print (type({}))

<class 'int'>
<class 'list'>
<class 'tuple'>
<class 'dict'>


## Class
***
All of the above, in the previous cell, are objects, so how can we create our own Object types? That is where the **class** keyword comes in.

The user defined objects are created using the class keyword. The class is a blueprint that defines a nature of a future object. From classes we can construct instances. An instance is a specific object created from a particular class. 

Let see how we can use class:

In [3]:
# Create a new object type called Sample
class Sample(object):
    pass

# Instance of Sample
x = Sample()

print (type(x))

<class '__main__.Sample'>


Note how x is now the reference to our new instance of a Sample class. In other words, we **instantiate** the Sample class.

Inside of the class we currently just have pass. But we can define class attributes and methods.

An **attribute** is a characteristic of an object.
A **method** is an operation we can perform with the object.

For example we can create a class called Dog. An attribute of a dog may be its breed or its name, while a method of a dog may be defined by a .bark() method which returns a sound.

Let's get a better understanding of attributes through an example.

## Attributes
The syntax for creating an attribute is:
    
    self.attribute = something
    
There is a special method called:

    __init__()

which is used to initialize the attributes of an object. For example:

In [15]:
class Dog(object):
    def __init__(self,breed): #self shoud be the first argument always in the __init__ method.
        self.breed = breed
        
sam = Dog(breed='Lab') # Instance 1. Copy one of the class Dog
frank = Dog(breed='Huskie') # Instance 2. Copy two of the class Dog

Lets break down what we have above.The special method

    __init__() 

is called automatically right after the object has been created:

    def __init__(self, breed):
Each attribute in a class definition begins with a reference to the instance object. It is by convention named self. The breed is the argument. The value is passed during the class instantiation.

     self.breed = breed
Now we have created two instances of the Dog class. With two breed types, we can then access these attributes like this:     

In [16]:
sam.breed

'Lab'

In [18]:
frank.breed

'Huskie'

Note how we don't have any parenthesis after breed, this is because it is an attribute and doesn't take any arguments.

## Methods

Methods are functions defined inside the body of a class. They are used to perform operations with the attributes of our objects. Methods are essential in encapsulation concept of the OOP paradigm. This is essential in dividing responsibilities in programming, especially in large applications.

You can basically think of methods as functions acting on an Object that take the Object itself into account through its self argument.

Let's see the explanation and go through an example of creating a Circle class

<img src="../images/icon/Concept-Alert.png" alt="Concept-Alert" style="width: 100px;float:left; margin-right:15px"/>
<br />

### Explanation
***
- **`self`** is similar to the **`this`** pointer in other languages, except that (1) it needs to be explicitly passed as the first parameter of the instance method, and (2) is not a reserved keyword

- The **`__init__`** method is an initializer (_not_ constructor) and called on instantiation

- The **`__str__`** method is equivalent to toString()

- The **`__repr__`** method defines how the object is represented on console

In [19]:
class Circle(object):
    pi = 3.14 #This is a Class-Object attribute.
              #It remains same for all the methods within the class

    # Circle get instantiated with a radius (default is 1)
    def __init__(self, radius=1):
        self.radius = radius 

    # Area method calculates the area. Note the use of self.
    def area(self):
        return self.radius * self.radius * Circle.pi

    # Method for resetting Radius
    def setRadius(self, radius):
        self.radius = radius

    # Method for getting radius (Same as just calling .radius)
    def getRadius(self):
        return self.radius


c = Circle()

c.setRadius(4)
print ('Radius is: ',c.getRadius())
print ('Area is: ',c.area())

Radius is:  4
Area is:  50.24


<img src="../images/icon/Concept-Alert.png" alt="Concept-Alert" style="width: 100px;float:left; margin-right:15px"/>
<br />

## Instance vs Class vs Static Methods
***
- Instance methods have access to the **instance** of the class
- Class methods have access to the **class** (classes are also objects in Python), but not instances. This is similar to the static methods in Java/C#
- Static methods have no access to either instances or classes. They are more like plain functions, just bounded with the class for scoping

In [20]:
class MyClass:
    def instance_method(self):
        print('instance method called', self)

    @classmethod
    def class_method(cls):
        print('class method called', cls)

    @staticmethod
    def static_method():
        print('static method called')

obj = MyClass()

obj.instance_method()
MyClass.class_method()
MyClass.static_method()

instance method called <__main__.MyClass object at 0x00000205EBF1BC50>
class method called <class '__main__.MyClass'>
static method called


# some oop example:

In [22]:
class Person(object):
    def __init__(self,name,title,gender):
        self.name=name
        self.title=title
        self.gender=gender
    def display_name(self):
        return self.name+' '+self.title
    def isgender(self):
        return self.gender
    def change_first_name(self,new_name):
        self.name=new_name
    def change_title(self,new_title):
        self.title=new_title
p=Person('Rita','Roy','female')
print(p.display_name())
print('='*30)
p.change_first_name('Amrita')
p.change_title('Ganguly')
print(p.display_name())
print(p.isgender())

Rita Roy
Amrita Ganguly
female


In [23]:
class Laptop:
    def __init__(self,brand,name,price):
        self.brand=brand
        self.name=name
        self.price=price
        self.laptop_name=brand+' '+name
laptop1=Laptop('hp','au114tx',63000)
print(laptop1.laptop_name)

hp au114tx


In [25]:
class Person:
    def __init__(self,firstname,lastname,age):
        self.firstname=firstname
        self.lastname=lastname
        self.age=age
    def fullname(self):
        return f"{self.firstname} {self.lastname}"
    def isabove18(self):
        return self.age>18
p1=Person('Sajib','Halder',15)
p2=Person('AJIB','HALDER',30)
print(p1.isabove18())
print(p2.fullname())

False
AJIB HALDER


In [26]:
class Laptop:
    def __init__(self,brand,modelname,price):
        self.brand=brand
        self.name=modelname
        self.price=price
        self.laptop_name=brand+' '+modelname
    def apply_discount(self,num):
        off_price=(num/100)*self.price
        return self.price-off_price
laptop1=Laptop('hp','au114tx',63000)
print(laptop1.laptop_name)
print(laptop1.apply_discount(10))

hp au114tx
56700.0


In [32]:
class Laptop:
    discount_percent=10
    def __init__(self,brand,modelname,price):
        self.brand=brand
        self.name=modelname
        self.price=price
        self.laptop_name=brand+' '+modelname
    def apply_discount(self):
        off_price=(Laptop.discount_percent/100)*self.price
        return self.price-off_price
laptop1=Laptop('hp','au114tx',63000)
print(laptop1.laptop_name)
print(laptop1.apply_discount())
Laptop.discount_percent=90
print(laptop1.__dict__)
print(laptop1.apply_discount())

hp au114tx
56700.0
{'brand': 'hp', 'name': 'au114tx', 'price': 63000, 'laptop_name': 'hp au114tx'}
6300.0


In [44]:
class Person:
    count_instance=0
    def __init__(self,firstname,lastname,age):
        Person.count_instance +=1
        self.firstname=firstname
        self.lastname=lastname
        self.age=age
p1=Person('sajib','halder',30)
p2=Person('sajib','halder',30)
p2=Person('sajib','halder',30)
print(Person.count_instance)

3


In [50]:
class Person:
    count_inst=0
    def __init__(self,firstname,lastname,age):
        Person.count_inst +=1
        self.firstname=firstname
        self.lastname=lastname
        self.age=age
    @classmethod
    def count_instance(cls):
        return f"you have created {cls.count_inst} instances of {cls.__name__}class"
    def fullname(self):
        return f"{self.firstname} {self.lastname}"
    def isabove18(self):
        return self.age>18
p1=Person('sajib','halder',28)
p2=Person('sajib','halder',30)
print(Person.count_instance())

you have created 2 instances of Personclass


# class method as a constructor:

In [52]:
class Person:
    count_inst=0
    def __init__(self,firstname,lastname,age):
        Person.count_inst +=1
        self.firstname=firstname
        self.lastname=lastname
        self.age=age
    @classmethod
    def from_string(cls,string):
        first,last,age=string.split(',')
        return cls(first,last,age)
    @classmethod
    def count_instance(cls):
        return f"you have created {cls.count_inst} instances of {cls.__name__}class"
    def fullname(self):
        return f"{self.firstname} {self.lastname}"
    def isabove18(self):
        return self.age>18
p1=Person('sajib','halder',28)
p2=Person('sajib','halder',30)
p3=Person.from_string('sajib,halder,30')
print(p3.fullname())
print(Person.count_instance())

sajib halder
you have created 3 instances of Personclass


In [53]:
class Person:
    count_inst=0
    def __init__(self,firstname,lastname,age):
        Person.count_inst +=1
        self.firstname=firstname
        self.lastname=lastname
        self.age=age
    @classmethod
    def from_string(cls,string):
        first,last,age=string.split(',')
        return cls(first,last,age)
    @classmethod
    def count_instance(cls):
        return f"you have created {cls.count_inst} instances of {cls.__name__}class"
    @staticmethod
    def hello():
        print("hello,static method called")
    def fullname(self):
        return f"{self.firstname} {self.lastname}"
    def isabove18(self):
        return self.age>18
p1=Person('sajib','halder',28)
p2=Person('sajib','halder',30)
p3=Person.from_string('sajib,halder,30')
print(p3.fullname())
print(Person.count_instance())
print(Person.hello())

sajib halder
you have created 3 instances of Personclass
hello,static method called
None


# Encapsulation,Abstraction,Inheritance,Operator overloading,Polymorphism:

In [56]:
# 1.Encapsulation
# 2.Abstraction
# 3.Naming convention,Naming Mangling
# 4.oop propertyy & setter Decorator
# 5.Inheritance / multilevel inheritance / multiple inheritance
# 6.special magic/dunder method
# 7.operator overloading
# 8.polymorphism

In [ ]:
# encapsulation:
hiding the private details of a class from other objects
# abstraction:
is a method to hide internal functionalities from users.suppose you are going to an ATM to withdraw money.you simply insert your
card,click some buttons & get the money.you dont know what is happening internally.this is called abstraction.
suppose there is a tree.a tree have its components like root,stem,brances,leaves,flowers,fruits etc.it has some 
functionalities like photosynthesis.but in a single unit we call it as a tree.this is encapsulationi.e. to bind 
data members & functions in a single unit

In [ ]:
#name convention:
_name(it means that it is a private variable.please dont do any change to this).actually all are public in python.just to 
tell someone/developer thatplease dont modified this variable(it is act like a private variable)
__name__    called dunder/magic method
#name mangling:
_name of the class__class attribute name

In [57]:
class Phone:
    def __init__(self,brand,modelname,price):
        self.brand=brand
        self.modelname=modelname
        self._price=price
    def makeacall(self,phone_no):
        print(f"calling {phone_no}.....")
phone1=Phone('nokia','1100',2000)
print(phone1._price)

2000


In [64]:
class Phone:
    def __init__(self,brand,modelname,price):
        self.brand=brand
        self.modelname=modelname
        self._price=price
    def makeacall(self,phone_no):
        print(f"calling {phone_no}.....")
phone1=Phone('nokia','1100',2000)
print(phone1._price)
phone1.__dict__
print(phone1.__dict__)
#print(_phone__price)
phone1._phone__price=-700
print(phone1._phone__price)

2000
{'brand': 'nokia', 'modelname': '1100', '_price': 2000}
-700


In [97]:
class Phone:
    def __init__(self,brand,modelname,price):
        self.brand=brand
        self.modelname=modelname
        self._price=price
        self.complete_specifi= f"{self.brand} {self.modelname} and price is {self._price}"
    @property
    def complete_specification(self):
        return f"{self.brand} {self.modelname} and price is {self._price}"
    def make_a_call(self,phone_name):
        print(f"calling {phone_name}.....")
    def full_name(self):
        return f"{self.brand} {self.modelname}"
phone5=Phone('nokia','1100',-1500)
phone5._price=500
print(phone5._price)
print(phone5.complete_specification())
print(phone5.complete_specification)

500


TypeError: 'str' object is not callable

# NumPy

## NumPy Basics

![caption](../images/numpy-logo.jpg)
***
NumPy, which stands for Numerical Python, is a library consisting of multidimensional array objects and a collection of routines for processing those arrays. Using NumPy, mathematical and logical operations on arrays can be performed. In this part, along with the basics of NumPy such as its architecture and environment, we shall also discuss the various array functions, types of indexing, etc.

We can install numpy by `pip install numpy`

- Main object: **`ndarray`**

<img src="../images/icon/Technical-Stuff.png" alt="Technical-Stuff" style="width: 100px;float:left; margin-right:15px"/>
<br />

# ndarray
***

The most important object defined in NumPy is an N-dimensional array type called ndarray. It describes the collection of items of the same type. Items in the collection can be accessed using a zero-based index.

Every item in an ndarray takes the same size of block in the memory. Each element in ndarray is an object of data-type object (called dtype).Any item extracted from ndarray object (by slicing) is represented by a Python object of one of array scalar types. An instance of ndarray class can be constructed by different array creation routines described later.

You import the function in python by calling `import numpy`. The basic ndarray is created using an array function in NumPy as follows −

In [1]:
import numpy
numpy.array

<function numpy.core.multiarray.array>


<img src="../images/icon/Concept-Alert.png" alt="Concept-Alert" style="width: 100px;float:left; margin-right:15px"/>
<br />

## How do I create Arrays in Python?
***
* Create an array from a regular Python list or tuple using the array function. 

* The type of the resulting array is deduced from the type of the elements in the sequences

It creates an ndarray from any object exposing array interface, or from any method that returns an array.

In [2]:
import numpy as np

# From list: 1d array
my_list = [10, 20, 30]
np.array(my_list)

array([10, 20, 30])

In [3]:
# From list: 2d array
list_of_lists =  [[5, 10, 15], [20, 25, 30], [35, 40, 45]]
np.array(list_of_lists)

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [4]:
type(np.array(list_of_lists))

numpy.ndarray

An example of how does n-dimensional looks

## Types

![NumPy Array Types](../images/numpy-types1.jpg)

`ndarray` is also known by the alias `array`. Note that `numpy.array` is not the same as the Standard Python Library class `array.array`, which only handles one-dimensional arrays and offers less functionality. The more important attributes of an `ndarray` object are:

***ndarray.shape***
the dimensions of the array. This is a tuple of integers indicating the size of the array in each dimension. For a matrix with n rows and m columns, `shape` will be `(n,m)`. The length of the `shape` tuple is therefore the rank, or number of dimensions,`ndim`.

***ndarray.dtype***
an object describing the type of the elements in the array. One can create or specify dtype’s using standard Python types. Additionally NumPy provides types of its own. numpy.int32, numpy.int16, and numpy.float64 are some examples.

***ndarray.reshape***
Returns an array containing the same data with a new shape.

<img src="../images/icon/Technical-Stuff.png" alt="Technical-Stuff" style="width: 100px;float:left; margin-right:15px"/>
<br />

## numpy.dtype
***
<br/>
The data type or dtype describes the kind of elements that are contained within the array.

* **bool**: Boolean values
<br/><br/>

* **int**: Integer values. Can be int16, int32, or int64.


* **float**: Floating point values. Can be float16, float32, or float64.
<br/><br/>


* ** string**: Text. Can be string or unicode (this distinction is greatly simplified in Python 3)

## Let's try it ourselves!
***
### Create a vector from the list [10, 20, 30]. Print the dtype and shape.

In [5]:
my_list = [10, 20, 30]

arr = np.array(my_list)

print(arr.dtype)
print(arr.shape)
b=arr.reshape
print(b)

int32
(3,)
<built-in method reshape of numpy.ndarray object at 0x0000020CCA92D670>


### Important Concepts
***
#### Rank

NumPy’s main object is the homogeneous multidimensional array. It is a table of elements (usually numbers), all of the same type, indexed by a tuple of positive integers. In NumPy dimensions are called axes. The number of axes is rank.

For example, the coordinates of a point in 3D space [1, 2, 1] is an array of rank 1, because it has one axis. That axis has a length of 3. 

In the example below, the array has rank 2 (it is 2-dimensional). The first dimension (axis) has a length of 6, the second dimension has a length of 6.

In [6]:
a =  np.array([[1, 2, 3,4,5,6],[7,8,9,10,11,12]]) 
print(a)
print(a.reshape)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
<built-in method reshape of numpy.ndarray object at 0x0000020CCA92D620>


In [7]:
print(a.shape)
print(a.dtype)
print(a.reshape)
print(a)

(2, 6)
int32
<built-in method reshape of numpy.ndarray object at 0x0000020CCA92D620>
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


# Why it is useful: Memory-efficient container that provides fast numerical operations.

In [8]:
#python lists
L = range(1000)
%timeit [i**2 for i in L]

845 µs ± 57.3 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [9]:
a = np.arange(1000)
%timeit a**2

3.66 µs ± 232 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


# NumPy Built-in methods

## `arange`
***
arange(**[start,]** ***stop[, step,][, dtype]***) : Returns an array with evenly spaced elements as per the interval. The interval mentioned is half opened i.e. **[Start, Stop)** (similar to the Python **`range()`** function).

In [10]:
import numpy as np

np.arange(0, 5)

array([0, 1, 2, 3, 4])

## `zeros` and `ones`
***
Generate arrays of all zeros and ones

In [20]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [18]:
np.ones((2, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

## `eye`
***
Creates an **identity matrix** of given size. Identity matrix is one in which all the diagonal elements are 1s. Rest all of the elemnts are zeros 

In [21]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [12]:
#create array using diag function

a = np.diag([1, 2, 3, 4]) #construct a diagonal array.

a

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [13]:
np.diag(a)   #Extract diagonal

array([1, 2, 3, 4])

## `linspace`
***
Linspace: Return **evenly spaced** numbers over a specified interval.

    linspace(start, stop, num=50, endpoint=True, retstep=False)

* Will return `num` number of values
* Equally spaced samples in the closed interval [start, stop] or the half-open interval [start, stop)
* Closed or half-open interval depends on whether 'endpoint' is True or False.

In [11]:
# divide into 7 interval from 0 to 10
np.linspace(0, 10, 7)

array([ 0.        ,  1.66666667,  3.33333333,  5.        ,  6.66666667,
        8.33333333, 10.        ])

<img src="../images/icon/Concept-Alert.png" alt="Concept-Alert" style="width: 100px;float:left; margin-right:15px"/>
<br />

## How do I generate Random Numbers?
***
<br/>
Numpy also has lots of ways to create random number arrays of given shape

- **`rand`**:

`numpy.random.rand(d0, d1, …, dn)` Create an array of the given shape and populate it with random samples from a **uniform distribution**

- **`randn`**: 

`numpy.random.randn(d0, d1, …, dn)`creates an array of specified shape and fills it with random values as per **standard normal distribution**.

If positive arguments are provided, randn generates an array of shape (d0, d1, …, dn), filled with random floats sampled from a univariate “normal” (Gaussian) distribution of mean 0 and variance 1 (if any of the d_i are floats, they are first converted to integers by truncation).

A single float randomly sampled from the distribution is returned if no argument is provided.

- **`randint`**: 

Return random integers from the “discrete uniform” distribution of the specified dtype in the “half-open” interval [low, high). If high is None (the default), then results are from [0, low).

In [23]:
# random number (uniform distribution) array of shape (3 , 4)

np.random.rand(3, 4)

array([[0.28667551, 0.62374611, 0.71404414, 0.94905095],
       [0.3358022 , 0.70205833, 0.05603881, 0.64291086],
       [0.18395325, 0.75426391, 0.22247654, 0.01768609]])

In [24]:
# random number (standard normal distribution) array of shape (2, 3)

print (np.random.randn(2, 3))

[[-0.92880451  1.39778036  0.37049328]
 [ 0.54292285  0.17459694 -1.00538735]]


In [25]:
# 10 random integers between 4 (inclusive) to 40 (exclusive)

np.random.randint(4, 40, 10)

array([28, 14, 22, 27, 31, 25, 14, 14,  9, 35])

In [26]:
# 10 random integers upto 50 (exclusive). This makes the start value default to 0.
# The size parameter dictates the return array shape

np.random.randint(50, size=(4,4))

array([[ 4, 32, 49,  5],
       [ 0,  1, 46, 23],
       [37, 23, 20, 42],
       [36, 17, 45, 21]])

# Analyzing the Weather using NumPy

<center><img src="../images/weather.jpg" alt="Weather" style="width: 350px;"/></center><br/><br/>
Now it's time to use some of the data manipulation we've learnt to analyze a weather data set. <br/><br/>
We'll be working with **weather_small_2012.csv**, which contains weather data for each hour in 2012.
Since weather_small_2012.csv is a csv file, rows are separated by line breaks, and columns are
separated by commas:

```
Date/Time,Temp (C),Dew Point Temp (C),Rel Hum (%),Wind Spd (km/h),Visibility (km),Stn Press (kPa)
2012-01-01 00:00:00,-1.8,-3.9,86,4,8.0,101.24
2012-01-01 01:00:00,-1.8,-3.7,87,4,8.0,101.24
2012-01-01 02:00:00,-1.8,-3.4,89,7,4.0,101.26
2012-01-01 03:00:00,-1.5,-3.2,88,6,4.0,101.27
```

**To read csv file, we use:**

    numpy.genfromtxt(fileName, delimeter=",")

In [14]:
# read csv file
weather = np.genfromtxt("../data/weather_small_2012.csv", delimiter=",")

print (weather.dtype)
print (weather)

float64
[[   nan    nan    nan ...    nan    nan    nan]
 [   nan  -1.8   -3.9  ...   4.     8.   101.24]
 [   nan  -1.8   -3.7  ...   4.     8.   101.24]
 ...
 [   nan  -0.5   -1.5  ...  28.     4.8   99.95]
 [   nan  -0.2   -1.8  ...  28.     9.7   99.91]
 [   nan   0.    -2.1  ...  30.    11.3   99.89]]


In [15]:
print (weather[1])

[   nan  -1.8   -3.9   86.     4.     8.   101.24]


Many items in this dataset are nan.

* The entire first row is nan – headers are String.
* Some of the numbers are written like 1.98600000e+03.

The data type of world_milk is float. Because all of the values in a NumPy array have to have the same
data type, NumPy attempted to convert all of the columns to floats when they were read in.

** Reading In The Data Properly **

***
To read world_milk.csv file properly we will have to use correct data type and skip the header.
* genfromtxt() default dtype is float, it converts non-numeric value to nan (not a number)
* To avoid nan, we read values as |S20 (String of length 20) 

In [16]:
weather = np.genfromtxt("../data/weather_small_2012.csv", dtype='|S20', skip_header=1, delimiter=",")

print (weather.dtype)
print (weather[1])

|S20
[b'2012-01-01 01:00:00' b'-1.8' b'-3.7' b'87' b'4' b'8.0' b'101.24']


In [17]:
# Create an array of temperatures from the data set.

temperatures = weather[:,1].astype(np.float16)
print(temperatures)

dew_point_temperatures = weather[:,2].astype(np.float16)
print(dew_point_temperatures)

[-1.8 -1.8 -1.8 ... -0.5 -0.2  0. ]
[-3.9 -3.7 -3.4 ... -1.5 -1.8 -2.1]


<img src="../images/icon/Concept-Alert.png" alt="Concept-Alert" style="width: 100px;float:left; margin-right:15px"/>
<br />

# Operations with NumPy arrays
<br/>
***
NumPy provides a lot of built-in functionality for working with arrays.
**The important concepts to remember are**
- Any operation with a scalar number or a scalar function will cause that operation being computed for each element
- Any operation with two **compatible** (eg.: same shape) arrays will cause one-to-one element computations

<img src="../images/icon/Maths-Insight.png" alt="Technical-Stuff" style="width: 100px;float:left; margin-right:15px"/>
<br />

## Arithmetic (1/2)
***
### Vector Arithmetic
- All operations between arrays are **element-wise**
- This means that if you multiply two 2d vectors, it will **NOT** perform matrix multiplication

<img src="../images/icon/Maths-Insight.png" alt="Technical-Stuff" style="width: 100px;float:left; margin-right:15px"/>
<br />

## Arithmetic (2/2)
***
### Scalar Arithmetic
- Any operation of an array with a scalar will result in **element-wise** computation of that operation
- For example **`my_array + 2`** is the same as adding 2 to each element of array

### Calculate the Temperatures from the weather dataset in Fahrenheit

In [18]:
farenheit = (temperatures * 9 / 5) + 32
farenheit

array([28.77, 28.77, 28.77, ..., 31.1 , 31.64, 32.  ], dtype=float16)

### Addition

In [19]:
# Total temperature

# Vector Addition
print(temperatures + dew_point_temperatures)

# Scalar Addition
print(temperatures + 100)

[-5.7 -5.5 -5.2 ... -2.  -2.  -2.1]
[ 98.2  98.2  98.2 ...  99.5  99.8 100. ]


### Division

In [20]:
array1 = np.arange(1, 10, dtype=np.float16).reshape(3, 3)
array2 = np.arange(100, 109, dtype=np.float16).reshape(3, 3)

print(array1)
print(array2)

print(array2 / array1)  # Vector Division
print(array2 / 3)    # Scalar Division

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
[[100. 101. 102.]
 [103. 104. 105.]
 [106. 107. 108.]]
[[100.     50.5    34.   ]
 [ 25.75   20.8    17.5  ]
 [ 15.14   13.375  12.   ]]
[[33.34 33.66 34.  ]
 [34.34 34.66 35.  ]
 [35.34 35.66 36.  ]]


## Comparison

Comparing two numpy arrays for equality, element-wise

In [21]:
# Find those temperatures that are above 0 degrees Celcius

greater_than_0 = temperatures > 0

print(temperatures)
print(greater_than_0)

print(type(greater_than_0))
print(greater_than_0.dtype)

[-1.8 -1.8 -1.8 ... -0.5 -0.2  0. ]
[False False False ... False False False]
<class 'numpy.ndarray'>
bool


In [22]:
arr1 = np.random.randint(1, 10, 6).reshape(2, 3)
arr2 = np.random.randint(1, 10, 6).reshape(2, 3)

print(arr1)
print(arr2)

print(arr1 >= arr2)

[[3 2 8]
 [2 9 1]]
[[3 9 4]
 [5 7 6]]
[[ True False  True]
 [False  True False]]


In [26]:
a = np.array([1, 2, 3, 4]) #create an array

a + 1

array([2, 3, 4, 5])

In [27]:
a ** 2

array([ 1,  4,  9, 16], dtype=int32)

In [28]:
b = np.ones(4) + 1

a - b

array([-1.,  0.,  1.,  2.])

In [29]:
a * b

array([2., 4., 6., 8.])

In [30]:
# Matrix multiplication

c = np.diag([1, 2, 3, 4])

print(c * c)
print("*****************")
print(c.dot(c))

[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]
*****************
[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]


In [31]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 2, 2, 4])
a == b

array([False,  True, False,  True])

In [32]:
a > b

array([False, False,  True, False])

In [33]:
#array-wise comparisions
a = np.array([1, 2, 3, 4])
b = np.array([5, 2, 2, 4])
c = np.array([1, 2, 3, 4])

np.array_equal(a, b)

False

In [34]:
np.array_equal(a, c)

True

In [35]:
a = np.array([1, 1, 0, 0], dtype=bool)
b = np.array([1, 0, 1, 0], dtype=bool)

np.logical_or(a, b)

array([ True,  True,  True, False])

In [36]:
np.logical_and(a, b)

array([ True, False, False, False])

In [37]:
a = np.arange(5)

np.sin(a)   

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [38]:
np.log(a)

C:\Users\DELL\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436])

In [39]:
np.exp(a)   #evaluates e^x for each element in a given input

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [40]:
# Shape Mismatch:
a = np.arange(4)

a + np.array([1, 2])

ValueError: operands could not be broadcast together with shapes (4,) (2,) 

# Basic Reductions:

**computing sums**

In [41]:
x = np.array([1, 2, 3, 4])
np.sum(x)

10

In [42]:
#sum by rows and by columns

x = np.array([[1, 1], [2, 2]])
x

array([[1, 1],
       [2, 2]])

In [43]:
x.sum(axis=0)   #columns first dimension

array([3, 3])

In [44]:
x.sum(axis=1)  #rows (second dimension)

array([2, 4])

**Other reductions**

In [45]:
x = np.array([1, 3, 2])
x.min()

1

In [46]:
x.max()

3

In [47]:
x.argmin()# index of minimum element

0

In [48]:
x.argmax()# index of maximum element

1

**Logical Operations**

In [49]:
np.all([True, True, False])

False

In [50]:
np.any([True, False, False])

True

In [51]:
#Note: can be used for array comparisions
a = np.zeros((50, 50))
np.any(a != 0)

False

In [52]:
np.all(a == a)

True

In [53]:
a = np.array([1, 2, 3, 2])
b = np.array([2, 2, 3, 2])
c = np.array([6, 4, 4, 5])
((a <= b) & (b <= c)).all()

True

<img src="../images/icon/Technical-Stuff.png" alt="Concept-Alert" style="width: 100px;float:left; margin-right:15px"/>
<br />

## Aggregation 
* **`sum()`:** Computes the sum of all the elements in a vector, or the sum along a dimension in a matrix.
* **`mean()`:** Computes the average of all the elements in a vector, or the average along a dimension in a matrix.
* **`max()`/`min()`:** Identifies the maximum/minimum value among all the elements in a vector, or along a dimension in a matrix.
* **`argmax()`/`argmin()`:** Returns the index of maximum/minimum element.

In [23]:
# Find max, min, mean temperature
print('Max: ', temperatures.max())
print('Min: ', temperatures.min())
print('Mean: ', temperatures.mean())
print('Sum: ', temperatures.sum())

# Find index of max/min temperature
print('Argmax: ', temperatures.argmax())
print('Argmin: ', temperatures.argmin())

Max:  33.0
Min:  -23.3
Mean:  8.8
Sum:  inf
Argmax:  4143
Argmin:  344


C:\Users\DELL\Anaconda3\lib\site-packages\numpy\core\_methods.py:36: RuntimeWarning: overflow encountered in reduce
  return umr_sum(a, axis, dtype, out, keepdims, initial)


<img src="../images/icon/ppt-icons.png" alt="ppt-icons" style="width: 100px;float:left; margin-right:15px"/>
<br />


## Mini Challenge - 4  :  
***
Create a matrix from the list of lists [[5.3, 10.2, 15.1], [20.4, 25.3, 30.9], [35.4, 40.1,45.6]]. Print the dtype and shape. 

In [24]:
import numpy as np
l = np.matrix([[5.3, 10.2, 15.1], [20.4, 25.3, 30.9], [35.4, 40.1,45.6]])

print(l)
print()
print(l.dtype)
print()
print(l.shape)

[[ 5.3 10.2 15.1]
 [20.4 25.3 30.9]
 [35.4 40.1 45.6]]

float64

(3, 3)


<img src="../images/icon/ppt-icons.png" alt="ppt-icons" style="width: 100px;float:left; margin-right:15px"/>
<br />

## Mini Challenge - 5 : 
***
Create an ndimensional array from randomly genrated numbers of shape (3,4), then rehape the array to (4,3)


In [25]:
Array = np.random.rand(3,4)
print(Array)
print()
print(Array.reshape(4,3))

[[0.49676947 0.18674159 0.5395497  0.02107731]
 [0.50268248 0.07386066 0.8349576  0.65251995]
 [0.16985932 0.13296294 0.37528334 0.35446914]]

[[0.49676947 0.18674159 0.5395497 ]
 [0.02107731 0.50268248 0.07386066]
 [0.8349576  0.65251995 0.16985932]
 [0.13296294 0.37528334 0.35446914]]
